#DEFINE OUTPUTFILE	"c:\pizza.txt"
#DEFINE ERRLOGFILE	"c:\foxqcerr.txt"
#DEFINE MTX_CLASS	"MTXAS.APPSERVER.1"
#DEFINE FOXQC_APP	"QC1"
#DEFINE QC_MACHINE	""

#DEFINE CRLF 			CHR(13)+CHR(10)

#DEFINE S_OK			0
#DEFINE CONTEXT_E_ABORTED	-1
